services:
  db:
    image: postgres:16 # Pinned to version 16

    environment:
      POSTGRES_DB: TVandAds
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - 9999:5432 # Expose PostgreSQL on port 9999

    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - ./data:/docker-entrypoint-initdb.d/data
      - db_data:/var/lib/postgresql/data # Persist data

volumes:
  db_data: